# ==============================================================
# = Eureka Server Versione Base
# = Dash: http://localhost:8761
# ==============================================================
server:
  port: 8761
  tomcat:
    threads:
      max: 5

spring:
  application:
    name: EurekaServer

# ==============================================================
# = Eureka Parameters
# ==============================================================
eureka:
  instance:
    hostname: localhost
    #Specifica se la registrazione avviene tramite ip
    preferIpAddress: false
  # ==============================================================
  # = Impostazione Server
  # ==============================================================
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: true
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 60000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
  # ==============================================================
  # = Impostazione Client
  # ==============================================================
  client:
    #Un Servizio Eureka � escluso dalla registrazione in Eureka
    registerWithEureka: false
    #Non esegue la cache in locale
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

sicurezza:
  userpwd: ${uspwd}
  adminpwd: ${adpwd}

jasypt:
  encryptor:
    # password passata come variabile da linea di comando al comando mvn di build per produrre un jar con già valorizzata questa property. Es.: mvn clean install -Denpwd=123_Stella.
    password: ${enpwd}

# ==============================================================
# = Logs Parameters
# ==============================================================
logging:
  level:
    #org.springframework.cloud: DEBUG
    org.springframework.security: INFO